"""Persistent paper-portfolio state — the operational ledger.

The research loop produces *candidates*; this module is where one candidate
becomes an *account*. State lives in a single JSON file so it's diffable,
versionable, and human-auditable. Every change goes through ``mark_to_market``
or ``apply_fill`` so the equity history is always consistent with the trades.

Design choices:
  * Whole-share quantities only (matches IBKR cash-account semantics; fractional
    ETF shares vary by broker and complicate the audit trail).
  * Pending tickets are first-class: the morning guide writes them, the closeout
    fills them at the actual close (with a slippage drag). Untouched tickets
    don't silently fill — they just expire.
  * The active strategy is named in state, not chosen by code, so switching is
    an explicit human decision logged in git, not an LLM whim.
"""

from __future__ import annotations

import json
import os
from dataclasses import asdict, dataclass, field
from datetime import date, datetime
from typing import Iterable

from fund.tax import (LotPolicy, RealizedLot, TaxLot, realize_sale,
                      summarize_realized)

def _default_state_path() -> str:
    """Single source of truth for the state path; respects env override.

    FUND_PORTFOLIO_PATH lets a user run multiple accounts side by side
    (taxable / IRA / etc.) by pointing at different JSON files. The
    Next.js dashboard reads the same env var via FUND_PORTFOLIO_PATH
    to choose which account to view.
    """
    env = os.environ.get("FUND_PORTFOLIO_PATH")
    if env:
        return env
    return os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "portfolio_state.json")


STATE_PATH = _default_state_path()


@dataclass
class Position:
    qty: float = 0.0          # shares — float to support fractional (Alpaca, Schwab)
    avg_cost: float = 0.0     # $/share, weighted cost basis
    # Per-acquisition lots — list of TaxLot dicts when serialized to JSON.
    # The aggregate qty / avg_cost above stay synchronized for back-compat
    # with code that doesn't care about tax lots.
    lots: list = field(default_factory=list)   # list[TaxLot]

    def __post_init__(self):
        # When loaded from JSON, lots come in as dicts; coerce to TaxLot.
        coerced = []
        for l in self.lots:
            if isinstance(l, TaxLot):
                coerced.append(l)
            elif isinstance(l, dict):
                coerced.append(TaxLot(**l))
            else:
                raise TypeError(f"Position.lots accepts TaxLot or dict, got {type(l)}")
        self.lots = coerced


@dataclass
class Ticket:
    """An unfilled order. Generated by morning.py, filled by closeout.py."""
    ticket_id: str
    created: str            # ISO date the ticket was written
    symbol: str
    side: str               # "BUY" | "SELL"
    qty: float              # always > 0; side carries the sign. Fractional allowed.
    ref_price: float        # the price the guide used to size it
    rationale: str
    risk_max_loss: float
    status: str = "pending"  # pending | filled | rejected | expired
    fill_date: str = ""
    fill_price: float = 0.0
    slippage_bps: float = 0.0


@dataclass
class EquityPoint:
    date: str               # ISO
    cash: float
    position_value: float
    equity: float


@dataclass
class Portfolio:
    principal: float
    cash: float
    positions: dict[str, Position] = field(default_factory=dict)
    history: list[EquityPoint] = field(default_factory=list)
    pending: list[Ticket] = field(default_factory=list)
    filled: list[Ticket] = field(default_factory=list)
    active_strategy: str = "sixty_forty"
    active_strategy_params: dict = field(default_factory=dict)
    inception: str = ""
    last_marked: str = ""
    # Tax-lot bookkeeping
    lot_policy: str = LotPolicy.TAX_OPTIMAL.value  # fifo|lifo|hifo|lt_first|tax_optimal
    realized: list = field(default_factory=list)   # list[RealizedLot dicts]
    # Wash-sale tracking: symbol -> ISO date of most recent sell-at-loss
    last_loss_sales: dict = field(default_factory=dict)

    # --- accounting ---------------------------------------------------------
    def position_value(self, prices: dict[str, float]) -> float:
        return sum(p.qty * prices.get(sym, p.avg_cost)
                   for sym, p in self.positions.items() if p.qty)

    def equity(self, prices: dict[str, float]) -> float:
        return self.cash + self.position_value(prices)

    def mark_to_market(self, prices: dict[str, float], on: date) -> EquityPoint:
        pv = self.position_value(prices)
        pt = EquityPoint(date=on.isoformat(), cash=round(self.cash, 2),
                         position_value=round(pv, 2),
                         equity=round(self.cash + pv, 2))
        # idempotent per-date: replace any existing same-date point
        self.history = [h for h in self.history if h.date != pt.date] + [pt]
        self.history.sort(key=lambda h: h.date)
        self.last_marked = pt.date
        return pt

    def apply_fill(self, ticket: Ticket, fill_price: float, on: date,
                   slippage_bps: float = 5.0) -> None:
        """Commit a fill. Cash and position arithmetic; never bypasses the
        already-checked risk verdict at ticket creation time. Supports
        fractional share quantities. Maintains tax lots + wash-sale tracking."""
        if ticket.status != "pending":
            raise ValueError(f"cannot fill non-pending ticket {ticket.ticket_id}")
        sign = +1 if ticket.side == "BUY" else -1
        slip = fill_price * (slippage_bps / 1e4) * sign
        effective = fill_price + slip
        notional = effective * ticket.qty
        pos = self.positions.setdefault(ticket.symbol, Position())
        if ticket.side == "BUY":
            if notional > self.cash + 1e-6:
                ticket.status = "rejected"
                return
            # Add a new tax lot at the effective fill price
            pos.lots.append(TaxLot(date_acquired=on.isoformat(),
                                   qty=ticket.qty,
                                   cost_per_share=effective))
            new_qty = pos.qty + ticket.qty
            if new_qty > 0:
                pos.avg_cost = (pos.avg_cost * pos.qty + effective * ticket.qty) / new_qty
            pos.qty = new_qty
            self.cash -= notional
        else:  # SELL
            if ticket.qty > pos.qty + 1e-9:
                ticket.status = "rejected"
                return
            # Realize against tax lots using the configured policy
            policy = LotPolicy(self.lot_policy)
            new_lots, realized = realize_sale(
                pos.lots, ticket.qty, effective, on, policy=policy,
            )
            pos.lots = new_lots
            pos.qty -= ticket.qty
            self.cash += notional
            # Recompute avg_cost from remaining lots
            if pos.qty > 1e-9 and pos.lots:
                total_basis = sum(l.qty * l.cost_per_share for l in pos.lots)
                pos.avg_cost = total_basis / pos.qty
            else:
                pos.qty = 0.0
                pos.avg_cost = 0.0
                pos.lots = []
            # Record realized PnL + update wash-sale tracking
            for r in realized:
                self.realized.append({
                    "date_acquired": r.date_acquired,
                    "date_sold": r.date_sold,
                    "symbol": ticket.symbol,
                    "qty": r.qty,
                    "cost_per_share": r.cost_per_share,
                    "sale_price": r.sale_price,
                    "long_term": r.long_term,
                    "realized_pnl": round(r.realized_pnl, 4),
                })
                if r.realized_pnl < 0:
                    # Most-recent loss sale per symbol drives the wash window
                    self.last_loss_sales[ticket.symbol] = on.isoformat()
        ticket.status = "filled"
        ticket.fill_date = on.isoformat()
        ticket.fill_price = round(effective, 4)
        ticket.slippage_bps = slippage_bps
        self.filled.append(ticket)

    def expire_pending(self) -> int:
        n = 0
        for t in list(self.pending):
            if t.status == "pending":
                t.status = "expired"
                n += 1
        self.pending = []
        return n

    # --- I/O ----------------------------------------------------------------
    @classmethod
    def fresh(cls, principal: float, inception: date,
              strategy: str = "sixty_forty",
              params: dict | None = None) -> "Portfolio":
        return cls(principal=principal, cash=principal,
                   inception=inception.isoformat(),
                   active_strategy=strategy,
                   active_strategy_params=dict(params or {}))

    @classmethod
    def load(cls, path: str = STATE_PATH) -> "Portfolio":
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"no portfolio state at {path} — run fund.portfolio init first")
        with open(path) as f:
            raw = json.load(f)
        positions = {s: Position(**p) for s, p in raw.get("positions", {}).items()}
        history = [EquityPoint(**h) for h in raw.get("history", [])]
        pending = [Ticket(**t) for t in raw.get("pending", [])]
        filled = [Ticket(**t) for t in raw.get("filled", [])]
        return cls(
            principal=raw["principal"], cash=raw["cash"],
            positions=positions, history=history,
            pending=pending, filled=filled,
            active_strategy=raw.get("active_strategy", "sixty_forty"),
            active_strategy_params=raw.get("active_strategy_params", {}),
            inception=raw.get("inception", ""),
            last_marked=raw.get("last_marked", ""),
            lot_policy=raw.get("lot_policy", LotPolicy.TAX_OPTIMAL.value),
            realized=raw.get("realized", []),
            last_loss_sales=raw.get("last_loss_sales", {}),
        )

    def save(self, path: str = STATE_PATH) -> None:
        raw = {
            "principal": self.principal,
            "cash": round(self.cash, 4),
            "positions": {s: asdict(p) for s, p in self.positions.items() if p.qty},
            "history": [asdict(h) for h in self.history],
            "pending": [asdict(t) for t in self.pending],
            "filled": [asdict(t) for t in self.filled],
            "active_strategy": self.active_strategy,
            "active_strategy_params": self.active_strategy_params,
            "inception": self.inception,
            "last_marked": self.last_marked,
            "lot_policy": self.lot_policy,
            "realized": self.realized,
            "last_loss_sales": self.last_loss_sales,
        }
        with open(path, "w") as f:
            json.dump(raw, f, indent=2, sort_keys=False, default=str)


# --- track-record metrics ---------------------------------------------------

def daily_returns(history: Iterable[EquityPoint]) -> list[tuple[str, float]]:
    """Per-day return from the equity history. First point yields no return."""
    points = list(history)
    out: list[tuple[str, float]] = []
    for i in range(1, len(points)):
        prev = points[i - 1].equity
        if prev <= 0:
            continue
        out.append((points[i].date, points[i].equity / prev - 1.0))
    return out


def cumulative_return(history: Iterable[EquityPoint]) -> float:
    points = list(history)
    if len(points) < 2 or points[0].equity <= 0:
        return 0.0
    return points[-1].equity / points[0].equity - 1.0


def drawdown(history: Iterable[EquityPoint]) -> float:
    """Current drawdown from peak (in [0, 1])."""
    points = list(history)
    if not points:
        return 0.0
    peak = max(h.equity for h in points)
    if peak <= 0:
        return 0.0
    return max(0.0, (peak - points[-1].equity) / peak)


# --- CLI helpers ------------------------------------------------------------

def _cli_init() -> None:
    import sys
    principal = 25_000.0
    strategy = "sixty_forty"
    for i, a in enumerate(sys.argv):
        if a == "--principal" and i + 1 < len(sys.argv):
            principal = float(sys.argv[i + 1])
        elif a == "--strategy" and i + 1 < len(sys.argv):
            strategy = sys.argv[i + 1]
    if os.path.exists(STATE_PATH) and "--force" not in sys.argv:
        print(f"portfolio_state.json already exists; pass --force to overwrite")
        return
    pf = Portfolio.fresh(principal, date.today(), strategy=strategy)
    pf.save()
    print(f"initialized portfolio: ${principal:,.2f} cash, "
          f"strategy={strategy}, inception={pf.inception}")


def _cli_switch() -> None:
    """Switch the active strategy without losing positions/cash/history.

    Tomorrow's morning will compute targets under the new strategy and
    generate the BUY/SELL rotation tickets.
    """
    import sys
    strategy = ""
    params_json = "{}"
    for i, a in enumerate(sys.argv):
        if a == "--strategy" and i + 1 < len(sys.argv):
            strategy = sys.argv[i + 1]
        elif a == "--params" and i + 1 < len(sys.argv):
            params_json = sys.argv[i + 1]
    if not strategy:
        print("switch requires --strategy NAME")
        raise SystemExit(2)
    try:
        params = json.loads(params_json) if params_json else {}
    except json.JSONDecodeError as e:
        print(f"--params must be valid JSON: {e}")
        raise SystemExit(2)
    pf = Portfolio.load()
    # Validate the strategy resolves before committing the change
    try:
        from fund.strategy.registry import build as build_strategy
        build_strategy(strategy, params)
    except Exception as e:
        print(f"REJECTED: cannot build strategy {strategy!r}: {e}")
        raise SystemExit(3)
    old = pf.active_strategy
    pf.active_strategy = strategy
    pf.active_strategy_params = params
    pf.save()
    print(f"switched active strategy: {old} -> {strategy} "
          f"{params if params else ''}")


if __name__ == "__main__":
    import sys
    if "init" in sys.argv:
        _cli_init()
    elif "switch" in sys.argv:
        _cli_switch()
    else:
        try:
            pf = Portfolio.load()
            print(json.dumps({"cash": pf.cash, "positions": list(pf.positions),
                              "equity_points": len(pf.history),
                              "pending": len(pf.pending),
                              "filled": len(pf.filled),
                              "strategy": pf.active_strategy}, indent=2))
        except FileNotFoundError as e:
            print(e)
